### ISSUE TITLE
Extension Activation fails

### ISSUE THREAD

**Issue by DevOpsDCC** [vmware/vrealize-developer-tools#69]
Extension fails to activate with error
[2020-05-06 16:43:34.774] [exthost] [error] Activating extension vmware-pscoe.vrealize-developer-tools failed due to an error:
[2020-05-06 16:43:34.774] [exthost] [error] TypeError: Cannot read property 'profiles' of undefined
	at ConfigurationManager.forceLoadProfiles (c:\Users\***\.vscode\extensions\vmware-pscoe.vrealize-developer-tools-2.1.6\extension\out\client\system\ConfigurationManager.js:91:51)
	at activate (c:\Users\***\.vscode\extensions\vmware-pscoe.vrealize-developer-tools-2.1.6\extension\out\extension.js:29:19)

### Steps to Reproduce
Reload VS Code
**Expected behavior:** [What you expect to happen]
Load vRO and vRA environment in extension tab
**Actual behavior:** [What actually happens]
Nothing loads
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
#### Client

-   vRealize Developer Tools Version: 2.1.6
-   vRealize Build Tools Version: 1.7.1+
-   VSCode Version: 1.44.2
-   OS Version: Windows 10.0.18363

#### Server

-   vRealize Automation Version: 8.1.0.9326
-   vRealize Orchestrator Version: 8.1.0 (15962410)

**Comment by nblagoev** [comment]
How does your `~/.m2/settings.xml` file look like? It seems like it's either invalid XML or has a missing root `<settings>` tag

**Comment by DevOpsDCC** [comment]
Hey Nikolay,

Thanks for the response - below is the settings file.
Do I need, I will try adding the root settings tag.

<profile>
    <id>prod-vra</id>
    <properties>
        
        <vro.host>IP Address</vro.host>
        <vro.port>443</vro.port>
        <vro.username>XXXXXXXXX</vro.username>
        <vro.password>myPlainTextPass</vro.password>
        <vro.auth>basic</vro.auth> 
        <vro.tenant>vsphere.local</vro.tenant> 

        
        <vra.host>IP Address</vra.host>
        <vra.port>443</vra.port>
        <vra.username>configurationadmin@vsphere.local</vra.username>
        <vra.password>myPlainTextPass</vra.password>
        <vra.tenant>vsphere.local</vra.tenant>
    </properties>
</profile>

**Comment by DevOpsDCC** [comment]
sorry bad paste

`<profile>
    <id>prod-vra</id>
    <properties>
        
        <vro.host>10.27.120.27</vro.host>
        <vro.port>443</vro.port>
        <vro.username>administrator@vsphere.local</vro.username>
        <vro.password>myPlainTextPass</vro.password>
        <vro.auth>basic</vro.auth> 
        <vro.tenant>vsphere.local</vro.tenant> 

        
        <vra.host>10.27.120.27</vra.host>
        <vra.port>443</vra.port>
        <vra.username>configurationadmin@vsphere.local</vra.username>
        <vra.password>myPlainTextPass</vra.password>
        <vra.tenant>vsphere.local</vra.tenant>
    </properties>
</profile>`

**Comment by DevOpsDCC** [comment]
I added the <settings> tag and still get the error below
[2020-08-04 10:06:46.335] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/danielcc/.vscode/extensions/vmware-pscoe.vrealize-developer-tools-2.1.6/extension/out/extension
[2020-08-04 10:07:00.762] [exthost] [error] Activating extension vmware-pscoe.vrealize-developer-tools failed due to an error:
[2020-08-04 10:07:00.763] [exthost] [error] TypeError: Cannot read property 'profile' of undefined
	at ConfigurationManager.forceLoadProfiles (c:\Users\danielcc\.vscode\extensions\vmware-pscoe.vrealize-developer-tools-2.1.6\extension\out\client\system\ConfigurationManager.js:91:60)
	at activate (c:\Users\danielcc\.vscode\extensions\vmware-pscoe.vrealize-developer-tools-2.1.6\extension\out\extension.js:29:19)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

I am attaching my setings.xml as the paste is messing the formatting, had to convert to txt file extension.


[settings.txt](https://github.com/vmware/vrealize-developer-tools/files/5022569/settings.txt)

**Comment by nblagoev** [comment]
Hi, that's not a valid format either - it should follow the maven spec for settings.xml (https://maven.apache.org/settings.html)

You can see an example settings.xml with sample profiles in the vRealize Build Tools fling (https://labs.vmware.com/flings/vrealize-build-tools) - under docs/setup-workstation-maven.html
